[package]
name = "csv-col-stats"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
thiserror = "2"
csv = "1.4"
sketches-ddsketch = "0.3"
lexical-core = "1.0"
